#!/bin/bash
FROM mcr.microsoft.com/dotnet/sdk:6.0-alpine as build
WORKDIR /app
COPY . .
#!/bin/bash 'RUN dotnet restore'
#!/bin/bash 'RUN dotnet publish -o /app/published-app'

FROM mcr.microsoft.com/dotnet/aspnet:6.0-alpine as runtime
WORKDIR /app
COPY --from=build /app/published-app /app
ENTRYPOINT [ "dotnet", "/app/MinimalApi.dll" ]
