FROM mcr.microsoft.com/dotnet/sdk:6.0-bullseye-slim-arm32v7 as build
WORKDIR /app
COPY . .
#RUN ["dotnet", "restore"]
RUN dotnet restore
RUN dotnet build -r linux-arm
#RUN ["dotnet", "build"]
#run dotnet publish -c release -r linux-arm

FROM mcr.microsoft.com/dotnet/aspnet:6.0-bullseye-slim-arm32v7 as runtime
WORKDIR /app
COPY --from=build /app/published-app /app
ENTRYPOINT [ "dotnet", "/app/MinimalApi.dll" ]
